export jobid=`sbatch -p normal,bigmem -N 1 --cpus-per-task=1 --job-name=spm_segmentCAT12   -t 0-04:00:00 --mem=8G  -m block:block   -o /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/log-%A_%a  -e /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/err-%A_%a  --array=1-13  /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/do_job_array.sh |awk '{print $4}'` 
echo submitted job $jobid
export jobid=`sbatch -p normal,bigmem -N 1 --cpus-per-task=1 --job-name=spm_segmentCAT12   -t 0-04:00:00 --mem=8G  -m block:block   -o /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/log-%A_%a  -e /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/err-%A_%a  --array=1-13   --depend=afterok:$jobid  /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/do_job_array.sh |awk '{print $4}'` 
echo submitted job $jobid
export jobid=`sbatch -p normal,bigmem -N 1 --cpus-per-task=1 --job-name=spm_segmentCAT12   -t 0-04:00:00 --mem=8G  -m block:block   -o /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/log-%A_%a  -e /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/err-%A_%a  --array=1-13   --depend=afterok:$jobid  /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/do_job_array.sh |awk '{print $4}'` 
echo submitted job $jobid
export jobid=`sbatch -p normal,bigmem -N 1 --cpus-per-task=1 --job-name=spm_segmentCAT12   -t 0-04:00:00 --mem=8G  -m block:block   -o /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/log-%A_%a  -e /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/err-%A_%a  --array=1-1   --depend=afterok:$jobid  /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/do_job_array.sh |awk '{print $4}'` 
echo submitted job $jobid
export jobid=`sbatch -p normal,bigmem -N 1 --cpus-per-task=1 --job-name=spm_segmentCAT12   -t 0-04:00:00 --mem=8G  -m block:block   -o /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/log-%A_%a  -e /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/err-%A_%a  --array=1-13   --depend=afterok:$jobid  /network/lustre/iss02/home/ivan.mindlin/spm_segmentCAT12/do_job_array.sh |awk '{print $4}'` 
echo submitted job $jobid
